### ISSUE TITLE
Error when run the cli

### ISSUE THREAD

**Issue by JerryHuang-LE** [pgjones/quart-db#19]
Hi there,

I just want to run the `quart db-migrate` and `db-schema`, it will throw out the error like below:

```
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/workspaces/svc-recommendations/.venv/lib/python3.11/site-packages/quart/cli.py", line 175, in locate_app
    module = import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
```

Seems i have to name the the file as `app.py` and place it on the top level? I think if we could specify the path and file_name, that would be much better. What do you think?

Cheers mate

**Comment by pgjones** [comment]
You can use the `--app` argument for this e.g. `quart --app file:variable db-migrate`
